### ISSUE TITLE
Measurement errors are not added to voltage magnitude measurements

### ISSUE THREAD

**Issue by liangdong158** [AmateurZhang/MatIdentification#1]
https://github.com/AmateurZhang/MatIdentification/blob/2bb5e80a9e4c589abbd1133a31ad8cedc80b7717/pqloads.m#L195
If I understand correctly, measurement errors are not added to voltage magnitudes. This is unrealistic and will impact a lot on the identification results.

**Comment by AmateurZhang** [comment]
Voltage calculated by matpower is not actually accurate and controlled by parameter _pf.tol_ (converge threshold of Newton method). pf.tol is set as 10e-8 by default.  We reduce the parameter to 10e-3~10e-6 in the cases, and there would be large errors introducing to voltage measurements.

**Comment by liangdong158** [comment]
I am not sure if adding measurement errors in this way really adds some errors to voltage magnitudes (I strongly doubt it).  Also I have tested the codes and the performance deteriorates very quickly with even small measurement errors on voltage magnitudes (0.2% for example).

**Comment by AmateurZhang** [comment]
> I am not sure if adding measurement errors in this way really adds some errors to voltage magnitudes (I strongly doubt it). Also I have tested the codes and the performance deteriorates very quickly with even small measurement errors on voltage magnitudes (0.2% for example).

0.2% is huge for accurate voltage measurements. Usually, the maximum divergence of voltage magnitudes on a distribution network is less than 5%. 0.2/5 = 4%, but for voltages differences between two neighbor buses are only 5%/20 = .25%. The measurement errors is even greater than the difference. That why the researchers set voltage error as a small value, in area, such as topology identification, state estimations, etc. btw, for 0.2s meters , their measurement accuracy is usually around 0.01%.  

If you have learnt the details of N-R method, you must know why pf.tol controls the accuracy.

**Comment by AmateurZhang** [comment]
BTW，**col-linear problem** of voltage measurements is the critical one in this kind of researches. It makes $V^TV$ close to zero and significantly increased the error from V. L1 L2 are not work in this case.  The voltage impact base identification part, so in the paper we only say the method can overcome large PQ errors.

**Comment by AmateurZhang** [comment]
## About voltage measurement errors.

$(P/V)-(P/V^2).*\Delta V = GV+G\Delta V$

$P/V = GV + G\Delta V+(P/V^2).*\Delta V$

Equivalent to

$\Delta G V = G\Delta V+(P/V^2).*\Delta V = A(\Delta V)$, $A$ is linear.

$\Delta G VV^{T} = A(\Delta V)V^T$

$\Delta G = A(\Delta V)V^T(VV^{T})^{-1}$

part of $V^T(VV^{T})^{-1}$, RCOND =  1.005668e-20, $V$ highly collinear. E.g.

```matlab
ans =
   1.0e+04 *
  col 1 to 17
    0.2848    1.7571   -0.8573   -0.0109    0.4691    2.0527    1.5524    0.4890    0.0826    0.0486   -1.0333    0.8391   -0.6339   -0.1520   -0.7796    0.6374   -0.3169
   -0.4964   -3.0161    1.3841   -0.0767   -0.5716   -3.4297   -2.4248   -0.6401   -0.2916   -0.1537    1.7098   -1.2434    1.1726    0.1658    1.0987   -0.9209    0.5254
   -0.0741    0.1401    0.2239    0.0404   -0.2988    0.3257   -0.0050    0.0838    0.1075    0.2572   -0.1548   -0.3336   -0.3738    0.2014    0.1914   -0.0814    0.0718
    0.1378   -0.0779   -0.6289    0.2182    0.3441    0.1037    0.2927   -0.0782   -0.3646   -0.3837    0.1425    0.3957    0.4529   -0.0276   -0.5229    0.3283   -0.2087
   -0.0311    0.2782    0.1342   -0.2714    0.1969   -0.1720    0.0672  
```

Therefore, the voltage error would be enlarged by $1e^4\sim 1e^5$ times to the estimation of $G$ or $B$.  Therefore, the accuracy of voltage should be better than 0.01%. E.g. round voltage data to 0.0001 p.u., i.e., 1.0023 p.u. 10.023kV for 10kV grid.

Use *pf.tol* can remove $(P/V^2).*\Delta V$ and increase algorithm performances. We suggest *pf.tol* is better than $1e^{-4}$.

- Some voltage records: 
  - node 2
    -  0.9939    0.9939    0.9938    0.9939    0.9939    0.9936    0.9937    0.9934   
  - node 5
    - 0.9803    0.9804    0.9801    0.9798    0.9809    0.9809    0.9808    0.9807
  - node 18
    - 0.7882    0.7825    0.7721    0.7830    0.7678    0.7800    0.7701    0.7710    

IF we have theta, the problem would be a linear one. The current problem is much difficult than that one, and it has more strict assumptions.
